export const FETCH_DRINKS_DETAIL_REQUEST = 'FETCH_DRINKS_DETAIL_REQUEST'
export const FETCH_DRINKS_DETAIL_SUCCESS = 'FETCH_DRINKS_DETAIL_SUCCESS'
export const FETCH_DRINKS_DETAIL_FAILURE = 'FETCH_DRINKS_DETAIL_FAILURE'